# -*- coding: utf-8 -*-

from . import siswa
from . import orangtua
from . import ref_pekerjaan
from . import ref_pendidikan
from . import ref_propinsi
from . import ref_kota
from . import ref_kecamatan
from . import ref_tahunajaran
from . import biaya_tahunajaran
from . import komponen_biaya
from . import master_kelas
from . import ruang_kelas
from . import guru
from . import riwayat_pendidikan
from . import ref_dataumum
from . import guru_karyawan
from . import sekolah
from . import harga_khusus
from . import aspek_penilaian
from . import ref_jam_pelajaran
from . import mata_pelajaran
from . import jadwal_pelajaran
from . import tingkat_pendidikan
from . import organisasi
from . import ekstrakulikuler
from . import hr_employee
from . import mobile_fasilitas
from . import res_config_setting
from . import konfigurasi_jenjang
from . import activation_result_wizard
from . import jenis_pegawai
